### ISSUE TITLE
Packages Foundation and UIKit 

### ISSUE THREAD

**Issue by npagare** [susairajs/XamarinForms-SQLite#1]
Hi @susairajs , thank you for putting this sample app together for us.

I am using VS 2019 lastest community edition update.

My build is failing for iOS app. I see that in AppDelegate.cs you have referred two namespaces 
using Foundation; & using UIKit; Are you using any 3rd party API for Xamarin Forms that are missing in this repo ? Likewise for Android as well - MainActivity class is not able to resolve Xamarin.Forms. I have even tried upgrading XF to 3.6 and other android support packages as well.

Here is a screenshot of few errors - 
![image](https://user-images.githubusercontent.com/26844611/56934808-43299680-6ab3-11e9-9d58-62397228f40d.png)

Any thoughts?

**Comment by alphinoalex** [comment]
@IoTFier Clean and rebuild it.

**Comment by npagare** [comment]
@alphinoalex Thank you.
